"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.rooms = void 0;
exports.rooms = [
    {
        name: "Luxurious Beachfront Retreat with Ocean Views",
        pricePerNight: 275,
        description: "Indulge in the ultimate beachfront experience at this luxurious retreat! This spacious studio offers breathtaking ocean views and is just steps away from pristine beaches. Relax in style with modern amenities and easy access to popular attractions. Ideal for a romantic getaway or a solo escape.",
        address: "123 Oceanfront Avenue, Miami Beach, FL, 33139",
        guestCapacity: 1,
        numberOfBeds: 1,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: false,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/yddlusphavjbkm1lf9fe",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189904/pillow-assets/demo/yddlusphavjbkm1lf9fe.jpg",
            },
        ],
        category: "King",
        reviews: [],
    },
    {
        name: "Secluded Mountain Cabin with Panoramic Views",
        pricePerNight: 325,
        description: "Escape to the tranquility of the mountains with a stay at this picturesque farmhouse. This 2-story cabin offers a private hot tub, spacious backyard, and orchard. Perfect for a family or a group retreat. Enjoy the beauty of nature and create lasting memories in this charming Maine-style getaway.",
        address: "456 Mountain Ridge Road, Aspen, CO, 81611",
        guestCapacity: 2,
        numberOfBeds: 2,
        hasInternet: true,
        hasBreakfast: false,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/sr91mphs6tosndam3xgx",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704190412/pillow-assets/demo/sr91mphs6tosndam3xgx.jpg",
            },
            {
                public_id: "pillow-assets/demo/kfgu1mnh8bqsgiu1hij6",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704190414/pillow-assets/demo/kfgu1mnh8bqsgiu1hij6.jpg",
            },
        ],
        category: "Twins",
        reviews: [],
    },
    {
        name: "City-Center Haven with Hot Tub and River Views",
        pricePerNight: 150,
        description: "Experience the best of downtown living at this private getaway in the heart of Portsmouth! Beautifully furnished, this spacious home is perfectly suited for exploring historic landmarks, museums, and vibrant markets. Enjoy the hot tub with stunning river views after a day of sightseeing.",
        address: "789 Market Street, Portsmouth, NH, 03801",
        guestCapacity: 3,
        numberOfBeds: 2,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: true,
        isPetAllowed: true,
        hasRoomCleaning: false,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/glrrxkhlbp5ifdfj3sej",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189903/pillow-assets/demo/glrrxkhlbp5ifdfj3sej.jpg",
            },
        ],
        category: "King",
        reviews: [],
    },
    {
        name: "Spacious Suite in a Quiet Boston Neighborhood",
        pricePerNight: 95,
        description: "Discover comfort in our spacious suite featuring a queen bed and foldable sofa. Accommodates 2-3 adults with a maximum of four adults. Enjoy Irish-themed decor, a private bathroom, smart TV, mini-fridge, desk, and city views. Located on the 3rd floor with no elevator.",
        address: "224 Cherry St, Boston, MA, 02108",
        guestCapacity: 6,
        numberOfBeds: 3,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/oqzjozncij3gotcg9tjr",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189891/pillow-assets/demo/oqzjozncij3gotcg9tjr.jpg",
            },
            {
                public_id: "pillow-assets/demo/lfrdg6egqzdlryjxvgiz",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189883/pillow-assets/demo/lfrdg6egqzdlryjxvgiz.jpg",
            },
        ],
        category: "King",
        reviews: [],
    },
    {
        name: "Elegant Stay at Shangri-La Hotel, Washington",
        pricePerNight: 120,
        description: "Experience luxury in our spacious room with a queen bed and foldable sofa. Comfortably accommodates 2-3 adults with a maximum of four adults. Irish-themed decor, private bathroom, smart TV, mini-fridge, desk, and city views. Located on the 3rd floor with no elevator.",
        address: "4724 Luxury Lane, Washington, DC, 20001",
        guestCapacity: 2,
        numberOfBeds: 1,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/n83l52psxckuxczyqmpv",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704191628/pillow-assets/demo/n83l52psxckuxczyqmpv.jpg",
            },
        ],
        category: "Single",
        reviews: [],
    },
    {
        name: "Cozy Retreat at Hotel Chimayo de Santa Fe",
        pricePerNight: 75,
        description: "Unwind in our cozy room featuring a queen bed and foldable sofa. Comfortably accommodates 2-3 adults with a maximum of four adults. Irish-themed decor, private bathroom, smart TV, mini-fridge, desk, and city views. Located on the 3rd floor with no elevator.",
        address: "1029 Serenity Street, Santa Fe, NM, 87501",
        guestCapacity: 2,
        numberOfBeds: 2,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/aph83jmc1mvqytlpnwv2",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189865/pillow-assets/demo/aph83jmc1mvqytlpnwv2.jpg",
            },
        ],
        category: "Twins",
        reviews: [],
    },
    {
        name: "4-Star Comfort at Hotel Garni Ischgl",
        pricePerNight: 110,
        description: "Experience comfort in our spacious room featuring a queen bed and foldable sofa. Accommodates 2-3 adults with a maximum of four adults. Irish-themed decor, private bathroom, smart TV, mini-fridge, desk, and city views. Located on the 3rd floor with no elevator.",
        address: "2645 Serene Street, Ischgl, Austria, 6561",
        guestCapacity: 5,
        numberOfBeds: 3,
        hasInternet: true,
        hasBreakfast: true,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: false,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "ppillow-assets/demo/whq7lubtmvvpqey7uqam",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189868/pillow-assets/demo/whq7lubtmvvpqey7uqam.jpg",
            },
        ],
        category: "King",
        reviews: [],
    },
    {
        name: "Tranquil Retreat at The Spa at Base Camp",
        pricePerNight: 95,
        description: "Escape to tranquility in our spacious room featuring a queen bed and foldable sofa. Accommodates 2-3 adults with a maximum of four adults. Irish-themed decor, private bathroom, smart TV, mini-fridge, desk, and city views. Located on the 3rd floor with no elevator.",
        address: "3118 Serenity Lane, Base Camp, MN, 56332",
        guestCapacity: 2,
        numberOfBeds: 1,
        hasInternet: true,
        hasBreakfast: false,
        hasAirCondition: true,
        isPetAllowed: false,
        hasRoomCleaning: true,
        ratings: 0,
        numOfReviews: 0,
        images: [
            {
                public_id: "pillow-assets/demo/zji8dwkoxdcuhqtpis5k",
                url: "https://res.cloudinary.com/dy9jdltpw/image/upload/v1704189879/pillow-assets/demo/zji8dwkoxdcuhqtpis5k.jpg",
            },
        ],
        category: "King",
        reviews: [],
    },
];
